version: '3.1'

services:
  local_delivery_bot:
    container_name: local_delivery_bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - ".env"
    # bot start after load db
    networks:
      - botnet
  ld_redis:
    container_name: ld_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/data
    env_file:
      - ".env"
    entrypoint: redis-server --appendonly yes --requirepass $REDIS_PASS
    networks:
      - botnet

    restart: always
networks:
  botnet:
    # указывается драйвер сети
    driver: bridge

